site_name: "AJ tech notes"
site_url: "https://github.io/aj-learning" # Optional, update later

# Define the navigation sidebar structure
nav:
  - Home: index.md
  - REST: REST.md
  - Kafka: kafka.md

# Choose a theme (the clean, popular "material" theme is recommended)
theme:
  name: material
