site_name: "AJ tech notes"
site_url: "https://github.io/aj-learning" # Optional, update later

# Define the navigation sidebar structure
nav:
  - Home: index.md
  - REST: REST.md
  - Kafka: kafka.md
  - RAG: RAG.md
  - mysql:
      - Intro: mysql/readme.md
      - commands: mysql/commands.md
      - string functions: mysql/string functions.md
      - refine commands: mysql/refine commands.md
      - aggregate: mysql/aggregate.md
      - dates: mysql/dates.md
      - logical & comparator: mysql/logical & comparator.md
      - constraints & alter: mysql/constraints & alter.md
      - relations: mysql/relations.md
      - views & SQL modes & window functions: mysql/views & SQL modes & window functions.md
      - self SchemaDesign: mysql/self SchemaDesign.md
      - DB triggers: mysql/DB triggers.md

# Choose a theme (the clean, popular "material" theme is recommended)
theme:
  name: material
  features:
    - content.code.copy # Adds the one-click copy button
markdown_extensions:
  - pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets # Needed if you are using --8<-- file inclusion
  - pymdownx.superfences # Required for syntax highlighting and nested blocks
